<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1dfu5tx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1dfu5tx/appProdProjectContainer.php') {
    touch(__DIR__.'/Container1dfu5tx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container1dfu5tx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container1dfu5tx\appProdProjectContainer([
    'container.build_hash' => '1dfu5tx',
    'container.build_id' => '98a45e23',
    'container.build_time' => 1642322138,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1dfu5tx');
